name: Bible
main: com.crt.bplugin.Gensokyo
version: 0.1
commands:
  bible:
    description: 让圣经照亮生活
    usage: /<command> [player]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>